name: Auto Merge Dev to Main

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge dev into main
        run: |
          git merge origin/dev --no-ff -m "Auto-merge dev into main [CI success]"

      - name: Push changes using Personal Access Token
        env:
          TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main