name: Auto Merge Dev to Main

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  contents: write  # Memberikan izin push ke repository

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git config (commit identity)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Fetch and switch to main
        run: |
          git fetch origin
          git checkout main

      - name: Merge dev into main
        run: |
          git merge origin/dev --no-ff -m "Auto-merge dev into main [CI success]"

      - name: Push changes using Personal Access Token
        env:
          PAT: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git push origin main
