name: Terraform Deploy to GCP (Infra branch)

on:
  push:
    branches:
      - infra

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Write service account key file
        run: |
          echo "$GCP_SA_KEY" > sa-key.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="credentials=sa-key.json" -var="project=$GCP_PROJECT_ID"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="credentials=sa-key.json" -var="project=$GCP_PROJECT_ID"
