name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # JOB 1: HANYA UNTUK LINT DAN TEST
  setup-install-lint-and-test:
    name: Setup, Install, ESLint, and ViTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

  # JOB 2: HANYA UNTUK BUILD DAN PUSH IMAGE
  build-and-push:
    name: Build and Push Docker Image
    # Job ini baru berjalan setelah 'lint-and-test' berhasil
    needs: setup-install-lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build \
            --build-arg VITE_GPT_TOKEN=${{ secrets.GPT_TOKEN }} \
            -t ${{ secrets.DOCKER_USERNAME }}/pso-kelompok12:${{ steps.commit.outputs.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/pso-kelompok12:${{ steps.commit.outputs.sha }}

  # JOB 3: HANYA UNTUK DEPLOY (INI SAMA PERSIS SEPERTI MILIK ANDA)
  deploy:
    name: Deploy to Cloud Run
    # Job ini baru berjalan setelah 'build-and-push' berhasil
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run from DockerHub
        run: |
          gcloud run deploy pso-kelompok12 \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/pso-kelompok12:${{ steps.commit.outputs.sha }} \
            --region asia-southeast2 \
            --platform managed \
            --allow-unauthenticated
